texas:
  master:
    flop:
      check: 80
      threshold: 70, 80, 90
    turn:
      check: 60
      threshold: 70, 80, 90
    river:
      check: 40
      threshold: 80,90,95
displayer:   # 线条大坐标不变, 区块大坐标+1
  scan_interval: 1000   # millisecond
  anchor:   # 定位窗口配置
    delay: 3    # 取点倒计时
    fix: 10     # 边界兼容宽度
    methods:    # 定位检查方法
      - area: 1, 1, 131, 31
      - area: 512, 152, 574, 267
      # todo more methods
    allow_mistake: 100
  charactor_rate:
    spade:    # 黑桃
    heart:    # 红桃
    diamond:    # 方块
    club:     # 梅花
  check:    # 检查像素配置
    rgb_mistake: 100  # 允许容错 , 需要测试调整
    line_step: 1
  phase:    # 程序阶段
    main_page:
      name: main_page
      check:
        - point: 772, 148, 0xfde90b
        - point: 810, 265, 0xaa8ff7
        - point: 805, 384, 0x5ab4e7
      next:
        - watting
        - room_page
#      actions:
#        start:
#          - check:
#            - point: 772, 148, 0xfde90b
#          - act:
#            - move: 111, 111    # todo
#            - click: 111, 111
#          - check:
#            - point: 772, 148, 0xfde90b
#        showRoom:
#    room_page:
#      name: room_page
    waiting:
      name: waiting
      check:
        - point: 517, 129, 0xfdccb7
        - contain: 468, 388, 559, 404, 0x59775f
        - line: 567, 428, 694, 428, 0x1c7130
    playing:
      name: playing
      check:
        - line: 570, 418, 619, 418, 0xe6e6e6
        - line: 632, 418, 682, 418, 0xe6e6e6
  status:   # 游戏状态
    my_turn:    # 必须在watching之前
      name: my_turn
      check:
        - same: 511, 410, 506, 406
      next:
        - watching
        - finish
    watching:   # 游戏中，其他玩家行动
      name: watching
      check:
        - same: 567, 419, 684, 419, 0x1e6e2f
      next:
        - my_turn
#    finish:
#      name: finish
#      next:
#        - my_turn
#        - watching

#  operation:    # 操作定义配置
#    call_or_check:
#      check:
#      act:
#      check:
#    fold:
#      check:
#      act:
#      check:
#    raise:
#      check:
#      act:
#      check:
#      act:
#      check:
#    bet_5:
#      check:
#      act:
#      check:
#      act:
#      check:
#    bet_10:
#      check:
#      act:
#      check:
#      act:
#      check:
#    bet_25:
#      check:
#      act:
#      check:
#      act:
#      check:
#    bet_50:
#      check:
#      act:
#      check:
#      act:
#      check:
#    all_in:
#      check:
#      act:
#      check:
#      act:
#      check:
#      act:
#      check:
  ocr_area:
    total_coin: 899, 47, 1019, 74
    player_pool:
#      - 0, 0, 66, 21
      - 369, 384, 435, 405
      - 217, 357, 283, 378
      - 164, 295, 230, 316
      - 661, 196, 727, 217
      - 792, 299, 858, 320
      - 741, 356, 807, 377
    total_pool: 443, 191, 593, 210
    my_coin: 472, 506, 557, 526
    my_coin_live_color: 0xfcde8f
    my_coin_dead_color: 0x8a7754
    call_button: 652, 553, 796, 585
    blind_info: 413, 357, 620, 375
    my_card:
      - rank: 568, 420, 585, 444
        suit: 566, 444, 587, 463
      - rank: 630, 420, 646, 445
        suit: 629, 445, 649, 465
    common_card:
                       # 17  28
      - rank: 320, 257, 337, 285
                       # 21  23
        suit: 319, 286, 340, 309
      - rank: 400, 257, 417, 285
        suit: 399, 286, 420, 310
      - rank: 482, 257, 500, 285
        suit: 480, 286, 502, 309
      - rank: 562, 257, 580, 285
        suit: 561, 286, 581, 309
      - rank: 642, 257, 660, 285
        suit: 641, 286, 663, 309
  other:
    player_absent:  # check by line
      - 0, 0 # myself, always here
      - 278, 420, 291, 420, 0x146129
      - 31, 380, 40, 380, 0x2a1b32
      - 784, 90, 794, 90, 0x0f0915
      - 984, 317, 994, 317, 0x241621
      - 727, 434, 766, 434, 0x301e36
    player_remain:
      - 0, 0  # myself, using coin area
      - 308, 466
      - 155, 364
      - 816, 136
      - 871, 364
      - 861, 466
    player_remain_color: 0xfdfdfd
    turn:
                #  -5   -4
      - 511, 410, 506, 406
      - 233, 410, 228, 406
      - 79, 311, 74, 307
      - 740, 77, 732, 73
      - 940, 311, 935, 307
      - 786, 410, 781, 406

