texas:
  master:
    flop:
      check: 80
      threshold: 70, 80, 90
    turn:
      check: 60
      threshold: 70, 80, 90
    river:
      check: 40
      threshold: 80,90,95
displayer:   # 线条大坐标不变, 区块大坐标+1
  anchor:   # 定位窗口配置
    delay: 3    # 取点倒计时
    fix: 10     # 边界兼容宽度
    methods:    # 定位检查方法
      - area: 1, 1, 131, 31
      - area: 512, 152, 574, 267
  charactor_rate:
    spade:    # 黑桃
    heart:    # 红桃
    diamond:    # 方块
    club:     # 梅花
  check:    # 检查像素配置
    rgb_mistake: 100  # 允许容错 , 需要测试调整
    line_step: 1
  phase:    # 程序阶段
    main_page:
      name: main_page
      check:
        - point: 772, 148, 0xfde90b
        - point: 810, 265, 0xaa8ff7
        - point: 805, 384, 0x5ab4e7
      next:
        - watting
        - room_page
      actions:
        start:
          preCheck:
            - point: 772, 148, 0xfde90b
          operate:
            - move: 111, 111
            - click: 111, 111
          postCheck:
            - point: 772, 148, 0xfde90b
#        showRoom:
#    room_page:
#      name: room_page
    waiting:
      name: waiting
      check:
        - point: 517, 129, 0xfdccb7
        - contain: 468, 388, 559, 404, 0x59775f
        - line: 567, 428, 694, 428, 0x1c7130
#    playing: todo
#      name: playing
  status:   # 游戏状态
    watching:
      name: watching
      next:
        - my_turn
    my_turn:
      name: my_turn
      next:
        - watching
        - finish
    finish:
      name: finish
      next:
        - my_turn
        - watching

  operation:    # 操作定义配置
    call:
      preCheck:
      operate:
      postCheck:
    check:
      preCheck:
      operate:
      postCheck:
    fold:
      preCheck:
      operate:
      postCheck:
    raise:
      preCheck:
      operate:
      postCheck:
    bet_5:
      preCheck:
      operate:
      postCheck:
    bet_10:
      preCheck:
      operate:
      postCheck:
    bet_25:
      preCheck:
      operate:
      postCheck:
    bet_50:
      preCheck:
      operate:
      postCheck:
  ocr_area:
    total_coin: 899, 47, 1019, 74
    player_pool:
#      - 0, 0, 66, 21
      - 217, 357, 283, 378  # todo
      - 217, 357, 283, 378
      - 164, 295, 230, 316
      - 661, 196, 727, 217
      - 792, 299, 858, 320
      - 741, 356, 807, 377
    player_remain:
      - 0, 0 # todo
      - 0, 0 # todo
      - 129, 364
      - 789, 139
      - 896, 359
      - 835, 466
    player_remain_color: 0xdedede
    call_button: 0, 0, 0, 0 # todo
    my_card:
      - 0:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
      - 1:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
    common_card:
      - 0:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
      - 1:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
      - 2:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
      - 3:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo
      - 4:
        - 0, 0, 0, 0 # todo
        - 0, 0, 0, 0 # todo

