texas:
  master:
    flop:
      check: 80
      threshold: 70, 80, 90
    turn:
      check: 60
      threshold: 70, 80, 90
    river:
      check: 40
      threshold: 80,90,95
displayer:   # 线条大坐标不变, 区块大坐标+1
  anchor:   # 定位窗口配置
    delay: 3    # 取点倒计时
    fix: 10     # 边界兼容宽度
    methods:    # 定位检查方法
      - horizon: 0
      - horizon: 10
      - horizon: 20
      - vertical: 0
      - vertical: 10
      - vertical: 20
      - line: 0, 0, 162, 70 # x1, y1, x2, y2
      - line: 162, 0, 0, 70 # x1, y1, x2, y2
      - area: 30, 20, 130, 50 # x1, y1, x2, y2
  charactorRate:
    1: 0.31
    2: 0.41
    3:
    4:
    5:
    6:
    7:
    8:
    9:
    0:
    J:
    Q:
    K:
    spade:    # 黑桃
    heart:    # 红桃
    diamond:    # 方块
    club:     # 梅花
    .:
    万:
    亿:
    弃:
    牌:
  check:    # 检查像素配置
    rgbMistake: 100  # 允许容错 , 需要测试调整
    lineStep: 1
  phase:    # 程序阶段
    main_page:
    waiting:
    watching:
    my_turn:
  status:   # 游戏状态

  operation:    # 操作定义配置


